# Generated by Django 5.2.14 on 2026-06-02 21:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discursos', '0003_webhooks_respostas_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemaDiscurso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField(unique=True, verbose_name='número')),
                ('titulo', models.CharField(max_length=255, verbose_name='título')),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'tema de discurso',
                'verbose_name_plural': 'temas de discursos',
                'ordering': ['numero'],
            },
        ),
        migrations.AlterField(
            model_name='discurso',
            name='tema',
            field=models.CharField(blank=True, max_length=200, verbose_name='tema manual'),
        ),
        migrations.AddField(
            model_name='discurso',
            name='tema_predefinido',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='discursos', to='discursos.temadiscurso', verbose_name='tema predefinido'),
        ),
    ]
